/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package figuras;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author victor
 */
public class MainForm extends javax.swing.JFrame {
    List<Dibujable> objetos;
    Imagen pajaro;
    javax.swing.Timer timer;

    /**
     * Creates new form NewJFrame
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciaObjetos() {
        final int k = 20;
        objetos = new ArrayList<>();
        Figura f;
        FiguraRellenable fr;
        // suelo
        f = new Linea(2 * k, 12 * k, 18 * k, 12 * k);
        f.setColor(Color.GREEN);
        f.setGrosor(2);
        objetos.add(f);

        // Cuerpo casa
        fr = new Rectangulo(4 * k, 6 * k, 6 * k, 6 * k);
        fr.setColorRelleno(Color.PINK);
        objetos.add(fr);
        
        // Puerta
        fr = new Rectangulo(5 * k, 8 *k, 2 * k, 4 *k);
        fr.setColorRelleno(Color.RED);
        objetos.add(fr);
        
        // Tejado
        f = new Linea(4 * k, 6 * k, 7 * k, 4 * k);
        f.setGrosor(3);
        f.setColor(Color.DARK_GRAY);
        objetos.add(f);
        f = new Linea(7 * k, 4 * k, 10 * k, 6 * k);
        f.setGrosor(3);
        f.setColor(Color.DARK_GRAY);
        objetos.add(f);

        // Sol
        f = new Linea(4*k, 3*k, 4*k, 5*k);
        f.setColor(Color.YELLOW);
        f.setGrosor(2);
        objetos.add(f);
        f = new Linea(3*k, 4*k, 5*k, 4*k);
        f.setColor(Color.YELLOW);
        f.setGrosor(2);
        objetos.add(f);
        fr = new Ovalo(4 * k, 4 * k, 1 * k, 1 * k);
        fr.setColorRelleno(Color.YELLOW);
        fr.setColor(Color.ORANGE);
        objetos.add(fr);

        pajaro = new Imagen("pajaro.png", 10 * k, 3 * k);
        objetos.add(pajaro);

        // Crear el timer y asociarlo a un método que dibuje
        // un fotograma
        int delay = 40; //milliseconds
        ActionListener task = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                dibujarFotograma(); 
            }
        };
        timer = new javax.swing.Timer(delay, task);
        timer.start();
    }

    public void dibujarFotograma() {
        Graphics2D g = (Graphics2D)jPanel1.getGraphics();
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, 400, 300);
        for (Dibujable d : objetos) {
            d.dibujar(g);
        }
        
        pajaro.setX((pajaro.getX()+3) % 400);
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        iniciaObjetos();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
